spring:
  application:
    name: Corporation
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

corporation:
  csv:
    base-url: https://www.ftc.go.kr/www/downloadBizComm.do
    referer: https://www.ftc.go.kr/www/selectBizCommOpenList.do?key=255
  cor:
    api:
      url: https://apis.data.go.kr/1130000/MllBsDtl_2Service/getMllBsInfoDetail_2
      key: tKgE3idpyMUHBymQyMbL1NR6x1HBcmdHH0rMuxe7FAiyKr1R98VXZiRrcHpAfMYmuHRK/wwoQ/6seZWe7Da4LA==

  adr:
    api:
      url: https://business.juso.go.kr/addrlink/addrLinkApi.do
      key: devU01TX0FVVEgyMDI1MDMyNTE1MTgxMTExNTU3NzE=

logging:
  level:
    com.work.company.application: debug